name: Build and Push to Artifact Registry
run-name: ${{ github.actor }} building ${{ github.repository }}

on:
  push:
    branches: ['master']

env:
  IMAGE_NAME: fetch-app
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_AGGREGATE: 1

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      #   - id: auth
      #     name: Auth
      #     run:
      #         echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ env.GITHUB_REGISTRY }}

      - id: docker-auth
        name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: gcr.io

      - id: build-and-push
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/<image-name>:<image-tag>

      - run: echo "This job's status is ${{ job.status }}."
