name: Build and Push to Artifact Registry
run-name: ${{ github.actor }} building ${{ github.repository }}

on:
  push:
    branches: ['master']

env:
  IMAGE_NAME: fetch-fe
  PROJECT_ID: ruvvet
  REGION: us-central1
  AR_URL: us-central1-docker.pkg.dev/ruvvet/fetch-fe
  SERVICE_ACCOUNT: github-actions@ruvvet.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/258552781147/locations/global/workloadIdentityPools/github-actions/providers/github-actions

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - id: docker-auth
        name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: us-central1-docker.pkg.dev

      - id: build-image
        name: Build Docker image
        run: docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}" ./

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - run: echo "This job's status is ${{ job.status }}."
