name: Build and Push to Artifact Registry
run-name: ${{ github.actor }} building ${{ github.repository }}

on:
  push:
    branches: ['master']

env:
  IMAGE_NAME: fetch-app
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_AGGREGATE: 1

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: build-and-push
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}>:next

      - run: echo "This job's status is ${{ job.status }}."
