name: Build and Push to Artifact Registry
run-name: ${{ github.actor }} building ${{ github.repository }}

on:
  push:
    branches: ['master']

env:
  IMAGE_NAME: fetch-app
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_AGGREGATE: 1

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}

      - id: push
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - run: echo "This job's status is ${{ job.status }}."
